trying build and push on docker hub

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,26 +10,33 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
 
-    - name: Set up Docker
-      uses: actions/setup-docker@v2
-      with:
-        dockerfile: Dockerfile  # Specify the path to your Dockerfile
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: Build Docker image
-      run: docker build -t goapp .
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-    - name: Run Docker container
-      run: docker run -d --name goapp -p 8000:8000 goapp
+      - name: Build and push
+        uses: docker/build-push-action@v5
+        with:
+          push: true
+          tags: user/app:latest
 
-    - name: Wait for container to start
-      run: sleep 10
+      - name: Run API Tests
+        run: |
+          timeout 10m bash api_tests.sh
+          if [ $? -ne 0 ]; then
+            echo "API tests failed."
+            exit 1
+          fi
 
-    - name: Run API Tests
-      run: |
-        bash api_tests.sh
-
-    - name: Stop Docker container
-      run: docker stop goapp
+      - name: Stop and Remove Docker container
+        run: |
+          docker stop goapp
+          docker rm goapp
